spring.application.name=authservice

server.port = 8081

#MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/auth_service
#spring.datasource.url=jdbc:mysql://host.docker.internal:3306/auth_service
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.session.jdbc.initialize-schema=always
jwt.expiration=604800000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

